import "./overlay"
import "./widgets"
import "./services"
import "./theme"
import "./theme"
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland

ShellRoot {
    id: root

    // Watch colors.json generated by matugen → push new values into Theme singleton
    FileView {
        id: themeFileWatcher
        path: Quickshell.shellPath("theme/colors.json")
        watchChanges: true
        onLoaded: applyColors()
        onTextChanged: applyColors()

        function applyColors() {
            var t = text().trim()
            if (t.length < 10) return
            try {
                var c = JSON.parse(t)
                if (c.background) Theme.background = c.background
                if (c.surface) Theme.surface = c.surface
                if (c.surfaceBright) Theme.surfaceBright = c.surfaceBright
                if (c.surfaceDim) Theme.surfaceDim = c.surfaceDim
                if (c.surfaceContainer) Theme.surfaceContainer = c.surfaceContainer
                if (c.surfaceVariant) Theme.surfaceVariant = c.surfaceVariant
                if (c.primary) Theme.primary = c.primary
                if (c.primaryFg) Theme.primaryFg = c.primaryFg
                if (c.secondary) Theme.secondary = c.secondary
                if (c.tertiary) Theme.tertiary = c.tertiary
                if (c.backgroundFg) Theme.backgroundFg = c.backgroundFg
                if (c.surfaceFg) Theme.surfaceFg = c.surfaceFg
                if (c.surfaceVariantFg) Theme.surfaceVariantFg = c.surfaceVariantFg
                if (c.outline) Theme.outline = c.outline
                if (c.outlineVariant) Theme.outlineVariant = c.outlineVariant
                if (c.error) Theme.error = c.error
            } catch (e) {
                console.error("theme colors parse error:", e)
            }
        }
    }

    // Only one PanelWindow which manages the Island and all Overlays
    PanelWindow {
        id: mainWindow
        anchors { top: true; left: true; right: true }
        
        // Keep the window large while animating to avoid stutter.
        // Shrink it 400ms after all overlays close so clicks can pass through to the desktop.
        property bool needsLargeWindow: overlayRoot.anyActive
        
        Timer {
            id: shrinkTimer
            interval: 400
            running: !overlayRoot.anyActive
            onTriggered: mainWindow.needsLargeWindow = false
        }
        
        Connections {
            target: overlayRoot
            function onAnyActiveChanged() {
                if (overlayRoot.anyActive) {
                    shrinkTimer.stop()
                    mainWindow.needsLargeWindow = true
                } else {
                    shrinkTimer.restart()
                }
            }
        }

        implicitHeight: needsLargeWindow ? 1080 : overlayRoot.childrenRect.height
        
        color: "transparent"
        WlrLayershell.exclusiveZone: 56
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: overlayRoot.anyActive ? WlrKeyboardFocus.Exclusive : WlrKeyboardFocus.None

        OverlayRoot {
            id: overlayRoot
            anchors.fill: parent
        }
    }

    Shortcut {
        sequences: ["Alt+F5"]
        onActivated: { /* Should forward to modeSvc if needed, or maybe handled elsewhere */ }
        context: Qt.ApplicationShortcut
    }
}
